# Generated by Django 5.0.4 on 2024-06-24 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('User_Name', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('Phone_No', models.CharField(max_length=12)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=8)),
                ('Address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_Name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Product_Desc', models.TextField()),
                ('Category', models.CharField(max_length=15)),
                ('Price', models.FloatField()),
                ('Stock', models.IntegerField()),
                ('Image', models.ImageField(max_length=255, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField()),
                ('Total_Price', models.FloatField()),
                ('Order_Date', models.DateField()),
                ('Shipping_Address', models.TextField()),
                ('User_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Keepsake.customer')),
                ('Product_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Keepsake.product')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField()),
                ('Rate', models.IntegerField()),
                ('Order_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Keepsake.order')),
                ('Product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Keepsake.product')),
            ],
        ),
    ]
