# Generated by Django 5.0.4 on 2024-06-24 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Keepsake', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Image',
        ),
    ]
