# Generated by Django 5.0.4 on 2024-06-25 03:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Keepsake', '0002_remove_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Order_Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
