# Generated by Django 5.0.4 on 2024-06-25 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Keepsake', '0003_alter_order_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Product_ID',
            new_name='Product_Name',
        ),
    ]
